### ISSUE TITLE
PyCrypto is death and has security problems. Please replace it.

### ISSUE THREAD

**Issue by ldsink** [yunify/qingstor-sdk-python#51]
I get an alert from Github. the reason is I installed this SDK and it's require PyCrypto.

![deepinscreenshot_select-area_20190107144402](https://user-images.githubusercontent.com/1937610/50753072-75f11a00-128b-11e9-97e0-e7535c4da38f.png)

I found that PyCrypto has alreay inactive since 2013. 

Please replace it by pycryptodome  or cryptography to solve the security problem.

**Comment by Xuanwo** [comment]
We use `PyCrypto` for the support of python 2.6 and 2.7, and we will find a way to fix it, thank you for your report.

**Comment by Xuanwo** [comment]
Closed for #54 has been merged.
